title: 3-Rocks-1-Paper
author: Gabriel Singh Bruno
email: gabriel.singhb@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Um blog de exploração de diversos temas dentro do game design
  com o objetivo de inspirar criatividade e criar discussão sobre
  todas as formas de jogos.
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 1
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/zappabad
      icon: twitter
      color: cyan
    - url: https://github.com/zappabad
      icon: github
      color: purple
    - url: https://discordapp.com/users/247560248712364034
      icon: discord
      color: blue
    - url: https://steamcommunity.com/id/Ssilhouette
      icon: steam
      color: yellow
    - url: https://www.linkedin.com/in/gabriel-singh-bruno-8b7a471b6/
      icon: linkedin
      color: blue
    - url: https://www.reddit.com/user/Ssilhouette
      icon: reddit
      color: red
    - url: https://www.twitch.tv/zappabad
      icon: twitch
      color: purple
    - url: https://www.youtube.com/channel/UCZjiRh1_sDyOFzAm4Enk64g
      icon: youtube
      color: red



  show_author: true

  animation_speed: 50

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
#avatar_source: github
#github_username: bitbrain
